import React, { useState, useCallback } from "react";
import { Plus, Trash2, Loader2, Save, Download, Send, ArrowLeft } from "lucide-react";
import { useCreateInvoiceMutation } from "../../../store/mainInvoiceApi";
import type { InvoiceStatus } from "../../../store/mainInvoiceApi";

// ─── Types ────────────────────────────────────────────────────────────────────

interface LineItem {
    id: string;
    description: string;
    additional_details: string;
    unit_price: number;
    qty: number;
    tax_percent: number;
    discount_percent: number;
}

interface FormState {
    // Header
    invoice_date: string;
    due_date: string;
    status: InvoiceStatus;
    terms: string;
    // Company (From)
    company_name: string;
    company_email: string;
    company_phone: string;
    company_address: string;
    company_business_number: string;
    // Customer (Bill To)
    customer_name: string;
    customer_email: string;
    customer_phone: string;
    customer_mobile: string;
    customer_fax: string;
    customer_address: string;
    // Pricing
    tax_type: "none" | "percent" | "fixed";
    tax_rate: number;
    discount_type: "none" | "percent" | "fixed";
    discount_value: number;
    // Footer
    notes: string;
    terms_conditions: string;
    authority_name: string;
    receiver_name: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const uid = () => Math.random().toString(36).slice(2, 9);

const fmt = (n: number) =>
    n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const defaultItem = (): LineItem => ({
    id: uid(),
    description: "",
    additional_details: "",
    unit_price: 0,
    qty: 1,
    tax_percent: 0,
    discount_percent: 0,
});

const inputCls =
    "w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm text-gray-700 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#2D8A75]/30 focus:border-[#2D8A75] transition-colors bg-white";

const labelCls = "block text-[11px] font-semibold text-gray-500 uppercase tracking-wide mb-1";

// ─── Props ────────────────────────────────────────────────────────────────────

interface Props {
    companyId: number;
    invoiceNo: string; // generated by backend preview or passed in
    onBack: () => void;
    onSuccess: () => void;
}

// ─── Component ────────────────────────────────────────────────────────────────

const AddInvoicePage: React.FC<Props> = ({ companyId, invoiceNo, onBack, onSuccess }) => {
    const [createInvoice, { isLoading }] = useCreateInvoiceMutation();

    const [items, setItems] = useState<LineItem[]>([defaultItem()]);
    const [errors, setErrors] = useState<Record<string, string>>({});

    const [form, setForm] = useState<FormState>({
        invoice_date: new Date().toISOString().split("T")[0],
        due_date: "",
        status: "draft",
        terms: "On Receipt",
        company_name: "",
        company_email: "",
        company_phone: "",
        company_address: "",
        company_business_number: "",
        customer_name: "",
        customer_email: "",
        customer_phone: "",
        customer_mobile: "",
        customer_fax: "",
        customer_address: "",
        tax_type: "none",
        tax_rate: 0,
        discount_type: "none",
        discount_value: 0,
        notes: "",
        terms_conditions: "",
        authority_name: "",
        receiver_name: "",
    });

    const set = (key: keyof FormState) => (
        e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
    ) => setForm(f => ({ ...f, [key]: e.target.value }));

    // ── Items ──
    const updateItem = useCallback((id: string, key: keyof LineItem, value: string | number) => {
        setItems(prev => prev.map(item => item.id === id ? { ...item, [key]: value } : item));
    }, []);

    const addItem = () => setItems(prev => [...prev, defaultItem()]);

    const removeItem = (id: string) => {
        if (items.length === 1) return;
        setItems(prev => prev.filter(i => i.id !== id));
    };

    // ── Totals ──
    const lineTotal = (item: LineItem) => {
        const base     = item.qty * item.unit_price;
        const disc     = base * (item.discount_percent / 100);
        const taxable  = base - disc;
        const tax      = taxable * (item.tax_percent / 100);
        return taxable + tax;
    };

    const subtotal = items.reduce((s, i) => s + i.qty * i.unit_price, 0);

    const discountTotal = (() => {
        if (form.discount_type === "percent") return subtotal * (form.discount_value / 100);
        if (form.discount_type === "fixed")   return Math.min(form.discount_value, subtotal);
        return 0;
    })();

    const taxableBase = subtotal - discountTotal;

    const taxTotal = (() => {
        if (form.tax_type === "percent") return taxableBase * (form.tax_rate / 100);
        if (form.tax_type === "fixed")   return Number(form.tax_rate);
        return 0;
    })();

    const grandTotal = taxableBase + taxTotal;

    // ── Validation ──
    const validate = () => {
        const e: Record<string, string> = {};
        if (!form.company_name.trim()) e.company_name = "Company name is required.";
        if (!form.customer_name.trim()) e.customer_name = "Customer name is required.";
        if (!form.invoice_date) e.invoice_date = "Invoice date is required.";
        if (items.some(i => !i.description.trim())) e.items = "All items must have a description.";
        if (items.some(i => i.unit_price <= 0)) e.items_price = "All items must have a price.";
        setErrors(e);
        return Object.keys(e).length === 0;
    };

    // ── Submit ──
    const handleSubmit = async (overrideStatus?: InvoiceStatus) => {
        if (!validate()) return;

        const fd = new FormData();
        const finalStatus = overrideStatus ?? form.status;

        const fields: Record<string, string> = {
            invoice_date:            form.invoice_date,
            due_date:                form.due_date,
            status:                  finalStatus,
            terms:                   form.terms,
            company_name:            form.company_name,
            company_email:           form.company_email,
            company_phone:           form.company_phone,
            company_address:         form.company_address,
            company_business_number: form.company_business_number,
            customer_name:           form.customer_name,
            customer_email:          form.customer_email,
            customer_phone:          form.customer_phone,
            customer_mobile:         form.customer_mobile,
            customer_fax:            form.customer_fax,
            customer_address:        form.customer_address,
            tax_type:                form.tax_type,
            tax_rate:                String(form.tax_rate),
            discount_type:           form.discount_type,
            discount_value:          String(form.discount_value),
            notes:                   form.notes,
            terms_conditions:        form.terms_conditions,
            authority_name:          form.authority_name,
            receiver_name:           form.receiver_name,
        };

        Object.entries(fields).forEach(([k, v]) => { if (v) fd.append(k, v); });

        items.forEach((item, i) => {
            fd.append(`items[${i}][description]`, item.description);
            fd.append(`items[${i}][additional_details]`, item.additional_details);
            fd.append(`items[${i}][qty]`, String(item.qty));
            fd.append(`items[${i}][unit_price]`, String(item.unit_price));
            fd.append(`items[${i}][tax_percent]`, String(item.tax_percent));
            fd.append(`items[${i}][discount_percent]`, String(item.discount_percent));
            fd.append(`items[${i}][sort_order]`, String(i + 1));
        });

        try {
            await createInvoice({ companyId, formData: fd }).unwrap();
            onSuccess();
        } catch {
            // global error handler
        }
    };

    // ─── Render ───────────────────────────────────────────────────────────────

    return (
        <div className="min-h-screen bg-[#F8F9FA] p-6 font-sans text-[#333333]">

            {/* Page Header */}
            <div className="flex justify-between items-center mb-6">
                <div className="flex items-center gap-3">
                    <button
                        onClick={onBack}
                        className="p-2 rounded-lg hover:bg-gray-200 transition-colors text-gray-500"
                    >
                        <ArrowLeft size={16} />
                    </button>
                    <h1 className="text-[15px] font-bold tracking-wide text-slate-800 uppercase">
                        New Invoice
                    </h1>
                </div>
                <div className="text-xs text-gray-500">
                    <span className="text-gray-400">Invoice</span>
                    <span className="mx-1">&gt;</span>
                    <span className="font-medium text-gray-700">New Invoice</span>
                </div>
            </div>

            {/* Main Card */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
                <div className="p-8 space-y-8">

                    {/* ── Section 1: Invoice Meta ── */}
                    <div className="grid grid-cols-2 gap-8">

                        {/* Left — Invoice fields */}
                        <div className="space-y-4">
                            <div>
                                <label className={labelCls}>Invoice No</label>
                                <div className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm font-mono font-bold text-gray-500 bg-gray-50">
                                    {invoiceNo || "Auto-generated"}
                                </div>
                            </div>

                            <div>
                                <label className={labelCls}>Invoice Date <span className="text-red-400">*</span></label>
                                <input
                                    type="date"
                                    value={form.invoice_date}
                                    onChange={set("invoice_date")}
                                    className={inputCls}
                                />
                                {errors.invoice_date && <p className="text-xs text-red-500 mt-1">{errors.invoice_date}</p>}
                            </div>

                            <div>
                                <label className={labelCls}>Due Date</label>
                                <input
                                    type="date"
                                    value={form.due_date}
                                    onChange={set("due_date")}
                                    min={form.invoice_date}
                                    className={inputCls}
                                />
                            </div>

                            <div>
                                <label className={labelCls}>Payment Status</label>
                                <select value={form.status} onChange={set("status")} className={inputCls}>
                                    <option value="draft">Draft</option>
                                    <option value="sent">Sent</option>
                                    <option value="paid">Paid</option>
                                    <option value="partial">Partial</option>
                                    <option value="overdue">Overdue</option>
                                    <option value="cancelled">Cancelled</option>
                                </select>
                            </div>

                            <div>
                                <label className={labelCls}>Terms</label>
                                <input
                                    type="text"
                                    value={form.terms}
                                    onChange={set("terms")}
                                    placeholder="e.g. On Receipt, Net 15"
                                    className={inputCls}
                                />
                            </div>
                        </div>

                        {/* Right — Company info */}
                        <div className="space-y-4">
                            <p className="text-[11px] font-bold text-gray-400 uppercase tracking-widest">From (Company)</p>
                            <div>
                                <label className={labelCls}>Company Name <span className="text-red-400">*</span></label>
                                <input type="text" value={form.company_name} onChange={set("company_name")} placeholder="Your Company Name" className={inputCls} />
                                {errors.company_name && <p className="text-xs text-red-500 mt-1">{errors.company_name}</p>}
                            </div>
                            <div>
                                <label className={labelCls}>Address</label>
                                <textarea rows={2} value={form.company_address} onChange={set("company_address")} placeholder="Company Address" className={inputCls + " resize-none"} />
                            </div>
                            <div className="grid grid-cols-2 gap-3">
                                <div>
                                    <label className={labelCls}>Email</label>
                                    <input type="email" value={form.company_email} onChange={set("company_email")} placeholder="email@company.com" className={inputCls} />
                                </div>
                                <div>
                                    <label className={labelCls}>Phone</label>
                                    <input type="text" value={form.company_phone} onChange={set("company_phone")} placeholder="+1 234 567 890" className={inputCls} />
                                </div>
                            </div>
                            <div>
                                <label className={labelCls}>Business / Tax Number</label>
                                <input type="text" value={form.company_business_number} onChange={set("company_business_number")} placeholder="123-45-6789" className={inputCls} />
                            </div>
                        </div>
                    </div>

                    {/* ── Divider ── */}
                    <div className="border-t border-gray-100" />

                    {/* ── Section 2: Bill To / Ship To ── */}
                    <div>
                        <p className="text-[11px] font-bold text-gray-400 uppercase tracking-widest mb-4">Bill To</p>
                        <div className="grid grid-cols-2 gap-8">

                            {/* Billing */}
                            <div className="space-y-3">
                                <div>
                                    <label className={labelCls}>Customer Name <span className="text-red-400">*</span></label>
                                    <input type="text" value={form.customer_name} onChange={set("customer_name")} placeholder="Client Full Name" className={inputCls} />
                                    {errors.customer_name && <p className="text-xs text-red-500 mt-1">{errors.customer_name}</p>}
                                </div>
                                <div>
                                    <label className={labelCls}>Address</label>
                                    <textarea rows={2} value={form.customer_address} onChange={set("customer_address")} placeholder="Billing Address" className={inputCls + " resize-none"} />
                                </div>
                                <div className="grid grid-cols-2 gap-3">
                                    <div>
                                        <label className={labelCls}>Email</label>
                                        <input type="email" value={form.customer_email} onChange={set("customer_email")} placeholder="client@email.com" className={inputCls} />
                                    </div>
                                    <div>
                                        <label className={labelCls}>Phone</label>
                                        <input type="text" value={form.customer_phone} onChange={set("customer_phone")} placeholder="(123) 456-7890" className={inputCls} />
                                    </div>
                                </div>
                                <div className="grid grid-cols-2 gap-3">
                                    <div>
                                        <label className={labelCls}>Mobile</label>
                                        <input type="text" value={form.customer_mobile} onChange={set("customer_mobile")} placeholder="(123) 456-7890" className={inputCls} />
                                    </div>
                                    <div>
                                        <label className={labelCls}>Fax</label>
                                        <input type="text" value={form.customer_fax} onChange={set("customer_fax")} placeholder="(123) 456-7890" className={inputCls} />
                                    </div>
                                </div>
                            </div>

                            {/* Tax / Discount config */}
                            <div className="space-y-4">
                                <p className="text-[11px] font-bold text-gray-400 uppercase tracking-widest">Tax & Discount</p>

                                <div className="grid grid-cols-2 gap-3">
                                    <div>
                                        <label className={labelCls}>Tax Type</label>
                                        <select value={form.tax_type} onChange={set("tax_type")} className={inputCls}>
                                            <option value="none">None</option>
                                            <option value="percent">Percent (%)</option>
                                            <option value="fixed">Fixed Amount</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label className={labelCls}>Tax Rate / Amount</label>
                                        <input
                                            type="number"
                                            min={0}
                                            value={form.tax_rate}
                                            onChange={e => setForm(f => ({ ...f, tax_rate: Number(e.target.value) }))}
                                            disabled={form.tax_type === "none"}
                                            className={inputCls + " disabled:bg-gray-50 disabled:text-gray-400"}
                                        />
                                    </div>
                                </div>

                                <div className="grid grid-cols-2 gap-3">
                                    <div>
                                        <label className={labelCls}>Discount Type</label>
                                        <select value={form.discount_type} onChange={set("discount_type")} className={inputCls}>
                                            <option value="none">None</option>
                                            <option value="percent">Percent (%)</option>
                                            <option value="fixed">Fixed Amount</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label className={labelCls}>Discount Value</label>
                                        <input
                                            type="number"
                                            min={0}
                                            value={form.discount_value}
                                            onChange={e => setForm(f => ({ ...f, discount_value: Number(e.target.value) }))}
                                            disabled={form.discount_type === "none"}
                                            className={inputCls + " disabled:bg-gray-50 disabled:text-gray-400"}
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* ── Divider ── */}
                    <div className="border-t border-gray-100" />

                    {/* ── Section 3: Line Items ── */}
                    <div>
                        <p className="text-[11px] font-bold text-gray-400 uppercase tracking-widest mb-4">Items</p>
                        {errors.items      && <p className="text-xs text-red-500 mb-2">{errors.items}</p>}
                        {errors.items_price && <p className="text-xs text-red-500 mb-2">{errors.items_price}</p>}

                        <div className="border border-gray-100 rounded-xl overflow-hidden">
                            {/* Table head */}
                            <div className="grid grid-cols-[2fr_1fr_1fr_1fr_1fr_auto] gap-0 bg-[#F8F9FA] border-b border-gray-100 text-[10px] font-bold uppercase tracking-widest text-gray-500 px-4 py-3">
                                <span>#&nbsp;&nbsp;Product Details</span>
                                <span className="text-right">Rate</span>
                                <span className="text-center">Qty</span>
                                <span className="text-right">Tax %</span>
                                <span className="text-right">Amount</span>
                                <span />
                            </div>

                            {/* Rows */}
                            {items.map((item, idx) => (
                                <div key={item.id} className="border-b border-gray-50 last:border-0">
                                    <div className="grid grid-cols-[2fr_1fr_1fr_1fr_1fr_auto] gap-0 items-start px-4 py-3">

                                        {/* Description */}
                                        <div className="pr-3">
                                            <div className="flex items-center gap-2 mb-1.5">
                                                <span className="text-[10px] font-bold text-gray-400 w-4">{idx + 1}</span>
                                                <input
                                                    type="text"
                                                    value={item.description}
                                                    onChange={e => updateItem(item.id, "description", e.target.value)}
                                                    placeholder="Product Name"
                                                    className="flex-1 border-0 border-b border-gray-200 pb-1 text-sm font-semibold text-gray-700 placeholder-gray-300 focus:outline-none focus:border-[#2D8A75] bg-transparent"
                                                />
                                            </div>
                                            <textarea
                                                rows={2}
                                                value={item.additional_details}
                                                onChange={e => updateItem(item.id, "additional_details", e.target.value)}
                                                placeholder="Product details (optional)"
                                                className="w-full ml-6 text-xs text-gray-400 placeholder-gray-300 border-0 focus:outline-none resize-none bg-transparent leading-relaxed"
                                            />
                                        </div>

                                        {/* Rate */}
                                        <div className="flex items-center justify-end pt-1">
                                            <input
                                                type="number"
                                                min={0}
                                                step={0.01}
                                                value={item.unit_price}
                                                onChange={e => updateItem(item.id, "unit_price", Number(e.target.value))}
                                                className="w-24 text-right border border-gray-200 rounded-lg px-2 py-1.5 text-sm focus:outline-none focus:ring-1 focus:ring-[#2D8A75]"
                                            />
                                        </div>

                                        {/* Qty */}
                                        <div className="flex items-center justify-center gap-1 pt-1">
                                            <button
                                                type="button"
                                                onClick={() => updateItem(item.id, "qty", Math.max(1, item.qty - 1))}
                                                className="w-6 h-6 rounded bg-gray-100 hover:bg-gray-200 text-gray-600 text-xs font-bold flex items-center justify-center transition-colors"
                                            >−</button>
                                            <input
                                                type="number"
                                                min={1}
                                                value={item.qty}
                                                onChange={e => updateItem(item.id, "qty", Math.max(1, Number(e.target.value)))}
                                                className="w-10 text-center border border-gray-200 rounded-lg py-1 text-sm focus:outline-none focus:ring-1 focus:ring-[#2D8A75]"
                                            />
                                            <button
                                                type="button"
                                                onClick={() => updateItem(item.id, "qty", item.qty + 1)}
                                                className="w-6 h-6 rounded bg-gray-100 hover:bg-gray-200 text-gray-600 text-xs font-bold flex items-center justify-center transition-colors"
                                            >+</button>
                                        </div>

                                        {/* Tax % */}
                                        <div className="flex items-center justify-end pt-1">
                                            <input
                                                type="number"
                                                min={0}
                                                max={100}
                                                value={item.tax_percent}
                                                onChange={e => updateItem(item.id, "tax_percent", Number(e.target.value))}
                                                className="w-16 text-right border border-gray-200 rounded-lg px-2 py-1.5 text-sm focus:outline-none focus:ring-1 focus:ring-[#2D8A75]"
                                            />
                                        </div>

                                        {/* Line Total */}
                                        <div className="flex items-center justify-end pt-2">
                                            <span className="text-sm font-bold text-gray-700">
                                                ${fmt(lineTotal(item))}
                                            </span>
                                        </div>

                                        {/* Delete */}
                                        <div className="flex items-center justify-end pt-1 pl-3">
                                            <button
                                                type="button"
                                                onClick={() => removeItem(item.id)}
                                                disabled={items.length === 1}
                                                className="p-1.5 bg-[#FFE4E6] hover:bg-red-100 text-[#F43F5E] rounded-lg transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
                                            >
                                                <Trash2 size={13} />
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>

                        {/* Add Item */}
                        <button
                            type="button"
                            onClick={addItem}
                            className="mt-3 flex items-center gap-1.5 text-sm text-[#2D8A75] font-medium hover:text-[#256d5e] transition-colors"
                        >
                            <Plus size={14} /> Add Item
                        </button>
                    </div>

                    {/* ── Totals ── */}
                    <div className="flex justify-end">
                        <div className="w-72 space-y-2">
                            <div className="flex justify-between text-sm text-gray-600 pb-2 border-b border-gray-100">
                                <span>Sub Total</span>
                                <span className="font-medium">${fmt(subtotal)}</span>
                            </div>
                            {form.tax_type !== "none" && (
                                <div className="flex justify-between text-sm text-gray-600">
                                    <span>Tax {form.tax_type === "percent" ? `(${form.tax_rate}%)` : "(fixed)"}</span>
                                    <span className="font-medium">${fmt(taxTotal)}</span>
                                </div>
                            )}
                            {form.discount_type !== "none" && (
                                <div className="flex justify-between text-sm text-gray-600">
                                    <span>Discount {form.discount_type === "percent" ? `(${form.discount_value}%)` : "(fixed)"}</span>
                                    <span className="font-medium text-[#F43F5E]">−${fmt(discountTotal)}</span>
                                </div>
                            )}
                            <div className="flex justify-between text-base font-bold text-gray-800 pt-2 border-t-2 border-[#2D8A75]/20">
                                <span>Total Amount</span>
                                <span className="text-[#2D8A75]">${fmt(grandTotal)}</span>
                            </div>
                        </div>
                    </div>

                    {/* ── Divider ── */}
                    <div className="border-t border-gray-100" />

                    {/* ── Section 4: Notes & Signatures ── */}
                    <div className="grid grid-cols-2 gap-8">
                        <div className="space-y-4">
                            <div>
                                <label className={labelCls}>Notes</label>
                                <textarea
                                    rows={4}
                                    value={form.notes}
                                    onChange={set("notes")}
                                    placeholder="Notes — any relevant information not covered, additional terms and conditions"
                                    className={inputCls + " resize-none"}
                                    maxLength={5000}
                                />
                                <p className="text-[10px] text-gray-400 text-right mt-0.5">{form.notes.length}/5000</p>
                            </div>
                            <div>
                                <label className={labelCls}>Terms & Conditions</label>
                                <textarea
                                    rows={3}
                                    value={form.terms_conditions}
                                    onChange={set("terms_conditions")}
                                    placeholder="Terms and conditions..."
                                    className={inputCls + " resize-none"}
                                />
                            </div>
                        </div>
                        <div className="space-y-4">
                            <div>
                                <label className={labelCls}>Authorized Signatory</label>
                                <input type="text" value={form.authority_name} onChange={set("authority_name")} placeholder="Authority Name" className={inputCls} />
                            </div>
                            <div>
                                <label className={labelCls}>Receiver Name</label>
                                <input type="text" value={form.receiver_name} onChange={set("receiver_name")} placeholder="Receiver Name" className={inputCls} />
                            </div>
                        </div>
                    </div>

                </div>

                {/* ── Action Bar ── */}
                <div className="border-t border-gray-100 bg-gray-50/50 px-8 py-4 flex items-center justify-end gap-3">
                    <button
                        type="button"
                        onClick={onBack}
                        disabled={isLoading}
                        className="px-4 py-2.5 border border-gray-200 text-gray-600 text-sm font-medium rounded-lg hover:bg-gray-100 transition-colors disabled:opacity-50"
                    >
                        Cancel
                    </button>
                    <button
                        type="button"
                        onClick={() => handleSubmit("draft")}
                        disabled={isLoading}
                        className="flex items-center gap-2 px-4 py-2.5 bg-white border border-gray-200 text-gray-700 text-sm font-medium rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-50"
                    >
                        {isLoading ? <Loader2 size={14} className="animate-spin" /> : <Save size={14} />}
                        Save Draft
                    </button>
                    <button
                        type="button"
                        onClick={() => handleSubmit("sent")}
                        disabled={isLoading}
                        className="flex items-center gap-2 px-5 py-2.5 bg-[#2D8A75] text-white text-sm font-medium rounded-lg hover:bg-[#256d5e] transition-colors disabled:opacity-50"
                    >
                        {isLoading ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />}
                        Send Invoice
                    </button>
                </div>
            </div>
        </div>
    );
};

export default AddInvoicePage;